# Generated by Django 5.2.15 on 2026-06-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sdm', models.CharField(max_length=64, unique=True)),
                ('nidn', models.CharField(blank=True, max_length=20, null=True)),
                ('nuptk', models.CharField(blank=True, max_length=20, null=True)),
                ('nip', models.CharField(blank=True, max_length=30, null=True)),
                ('nama', models.CharField(max_length=255)),
                ('status_aktif', models.CharField(blank=True, max_length=50, null=True)),
                ('status_pegawai', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_sdm', models.CharField(blank=True, max_length=50, null=True)),
                ('waktu_data_update', models.DateTimeField(blank=True, null=True)),
                ('sumber_data', models.CharField(default='SISTER', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
