# Generated by Django 5.2.15 on 2026-06-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinkronisasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanFungsional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jabfung', models.CharField(max_length=64, unique=True)),
                ('jabatan_fungsional', models.CharField(max_length=255)),
                ('sk', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('id_stat_pegawai', models.IntegerField(blank=True, null=True)),
                ('nm_stat_pegawai', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan', to='sinkronisasi.dosen')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
